apiVersion: v1
kind: Secret
metadata:
  name: chai-kafe-db-secret
  namespace: chaikafe
type: Opaque
stringData:
  DB_HOST: "mysql.cn6g4c2qk6wi.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: UGlkaWtpcmFsYQ==
#echo -n "<data>" | base64
