apiVersion: apps/v1
kind: Deployment
metadata:
  name: chai-kafe-app
  namespace: chai-kafe
  labels:
    app: chai-kafe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chai-kafe-app
  template:
    metadata:
      labels:
        app: chai-kafe-app
    spec:
      containers:
        - name: chai-kafe
          image: 561848282182.dkr.ecr.us-east-1.amazonaws.com/chai-kafe-app:7
          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
        
